__author__ = 'Zergling'

SCREEN_WIDTH = 960
SCREEN_HEIGHT = 480

MAP_WIDTH = 960
MAP_HEIGHT = 300

CELL_SIZE = 60
GRID_HEIGHT = 300

ATTACK_RATE = 0.8

INIT_SPAWN_RATE = 2.0
INIT_ITEM_RATE = 3.0

LEVEL_LENGTH = 120.0

SPAWN_CLOUD = 4.0
SPAWN_FEATURES = 2.5


NUM_ITEMS = 3
ITEMS = ['coins', 'skull', 'sword', 'health']